### ISSUE TITLE
Virtual Filesystem To-Do

### ISSUE THREAD

**Issue by nift4** [nift4/Valu#4]
- [ ] Remove multiple calls of the same function - cache the result instead
- [ ] Finish ramfs (File support not available yet)
- [ ] Test everything and fix bugs
